version: '3.6'

services:

  database:
    build: ./database/.
    ports:
      - "5432:5432"
    networks:
      - parking-network
    container_name: database

networks:
  parking-network:
    driver: bridge
    